DROP TABLE IF EXISTS "ods"."renshi_DEPARTMENT";
CREATE TABLE "ods"."renshi_DEPARTMENT" (
"CODEID" VARCHAR(20 ) NULL ,
"CODE" VARCHAR(100 ) NULL ,
"CHK_UNIT" INT NULL ,
"DESCRIPTION" VARCHAR(70 ) NULL ,
"ORDERSAME" INT NULL ,
"CPTR" CHAR(10 ) NULL ,
"SPELL" VARCHAR(70 ) NULL ,
"DTYPE" CHAR(4 ) NULL ,
"FLAG" VARCHAR(10 ) NULL ,
"STATUS" VARCHAR(255 ) NULL ,
"ALL_DESCRIPTION" VARCHAR(500 ) NULL ,
"APPENDIXCODE" VARCHAR(20 ) NULL ,
"AUDIT_INFO" VARCHAR(50 ) NULL ,
"CREATE_USER" INT NULL ,
"UNITID" VARCHAR(50 ) NULL ,
"PPTR" VARCHAR(50 ) NULL ,
"INCLUDE_UM" VARCHAR(2048 ) NULL ,
"SHORT_DESCRIPTION" VARCHAR(50 ) NULL ,
"EHRID" INT NULL ,
"HR" VARCHAR(10 ) NULL ,
"MYALL_DESCRIPTION" VARCHAR(500 ) NULL ,
"STAMP" VARCHAR(100 ) NULL ,
"HIDDEN" VARCHAR(10 ) NULL 
)DEFAULT CHARSET=utf8 COMMENT ='人事部门表';
;
