DROP TABLE  IF EXISTS "ods"."renshi_jzg_zzmm" ;
CREATE TABLE "ods"."renshi_jzg_zzmm" (
"B0110" VARCHAR(20 ) NULL ,
"A0100" VARCHAR(30 ) NULL ,
"STATUS" VARCHAR(10 ) NULL ,
"STATUS2" VARCHAR(255 ) NULL ,
"ID" INT NULL ,
"ORDERSAME" INT NULL ,
"A2205" VARCHAR(2 ) NULL ,
"A2230" VARCHAR(2 ) NULL ,
"A2210" VARCHAR(30 ) NULL COMMENT '参加年月',
"A2220" VARCHAR(30 ) NULL ,
"A2215" VARCHAR(70 ) NULL COMMENT '参加单位',
"A2235" VARCHAR(48 ) NULL ,
"USERID" INT NULL ,
"I_SERIAL" INT NULL ,
"I_RECORD" VARCHAR(30 ) NULL 
)DEFAULT CHARSET=utf8 COMMENT ='教职工政治面貌表';