DROP TABLE  IF  EXISTS "ods"."renshi_codeitem";
CREATE TABLE "ods"."renshi_codeitem" (
"CODEID" CHAR(10 ) NULL ,
"CODE" VARCHAR(20 ) NULL ,
"DESCRIPTION" VARCHAR(40 ) NULL ,
"PPTR" VARCHAR(20 ) NULL ,
"NOSHOW" CHAR(10 ) NULL ,
"CPTR" VARCHAR(20 ) NULL ,
"SPELL" VARCHAR(16 ) NULL ,
"STATUS" VARCHAR(50 ) NULL ,
"FLAG" CHAR(10 ) NULL ,
"LAYER" CHAR(10 ) NULL ,
"SHORTNAME" VARCHAR(40 ) NULL ,
"SYSTEM" CHAR(10 ) NULL ,
"KEY_WORD" VARCHAR(50 ) NULL 
)DEFAULT CHARSET=utf8 COMMENT ='人事系统代码表';