use ods;
DROP TABLE IF EXISTS ods.jw_XSXKB;
CREATE TABLE
IF NOT EXISTS ods.jw_XSXKB (
"XN" varchar(10) NOT NULL comment '099学年',
"XQ" varchar(1) NOT NULL comment '099学期',
"XKKH" varchar(50) NOT NULL comment '099选课课号',
"XH" varchar(20) NOT NULL comment '099学号',
"XM" varchar(50) NULL comment '099姓名',
"ZYMC" varchar(120) NULL comment '099专业名称',
"XSF" varchar(1) DEFAULT '1'  NULL comment '099选上否',
"LSH" int NULL comment '099流水号',
"JCYD" varchar(1) DEFAULT '1'  NULL comment '099教材预订',
"KSSJ" varchar(45) NULL comment '099考试时间',
"BZ" varchar(20) NULL comment '099备注',
"CXBJ" int(1) NULL comment '099重修标记',
"JSBH" varchar(10) NULL comment '099教室编号',
"JSMC" varchar(20) NULL comment '099教室名称',
"HKBJ" int(1) NULL comment '099缓考标记',
"BZ2" int(4) NULL comment '099备注2',
"XKLB" varchar(2) NULL comment '099学科类别',
"NJ" varchar(4) NULL comment '099年级',
"SKSJ" varchar(100) NULL comment '099上课时间',
"XKSJ" varchar(30) NULL comment '099选课时间',
"ZWH" varchar(4) NULL comment '',
"FXBJ" varchar(2) NULL comment '',
"SYXMBJ" varchar(4) NULL comment '',
"QZD" int DEFAULT 0  NULL comment '',
"BZXX" varchar(40) NULL comment '',
"TQXXBJ" varchar(2) NULL comment 'N99 提前选修标记',
"PJBH" varchar(200) NULL comment '',
"DJC" varchar(10) DEFAULT '1'  NULL comment 'N10可报名的轮次',
"SFKP" varchar(20) NULL comment '',
"BCXXBJ" varchar(2) NULL comment 'N99补修标记',
"SFKC" varchar(2) NULL comment '099是否可查',
"SFRYXXK" varchar(10) NULL comment '099是否任意选修课',
"SFZXCX" varchar(5) NULL comment 'N099是否自学重修',
"SFCZB" varchar(5) NULL comment 'N099是否重组班',
"CKBJ" varchar(10) NULL comment '099重考标记',
"ZY" varchar(4) NULL comment '099志愿',
"SXBJ" varchar(1) NULL comment '099刷选标记',
"DJCCX" varchar(2) DEFAULT '1'  NULL comment '099第几次重修报名',
"LRR" varchar(30) NULL comment '录入人',
"SFBZ" varchar(20) NULL comment '099身份备注',
"KSSJ_QZ" varchar(45) NULL comment '',
"JSBH_QZ" varchar(10) NULL comment '',
"JSMC_QZ" varchar(45) NULL comment '',
"ZWH_QZ" varchar(4) NULL comment '',
"BZ2_QZ" int(4) NULL comment '',
"XKNJ" varchar(10) NULL comment '选课年级',
"XKZYDM" varchar(10) NULL comment '选课专业代码',
"XKBJMC" varchar(10) NULL  comment '选课班级'
)DEFAULT CHARSET=utf8 COMMENT ='学生选课表';
