/*
#  DESCRIPTION: 
#
#      OPTIONS: ---
# REQUIREMENTS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: bi.yanbo@h3c.com
#      COMPANY: h3c.bigdata
#      VERSION: 1.0
#      CREATED: 2017/06/29
#     REVIEWER:
#     REVISION: ---
*/
DROP TABLE IF EXISTS GDM.EDU_GDM_YKT_JY_DA ;
CREATE TABLE IF NOT EXISTS GDM.EDU_GDM_YKT_JY_DA (
	XH VARCHAR (20) COMMENT '学号',
	XM VARCHAR (255) COMMENT '姓名',
	XBM VARCHAR (2) COMMENT '性别码',
	XBM_MC VARCHAR (2) COMMENT '性别',
	RXNY VARCHAR (6) COMMENT '入学年月',
	SZNJ VARCHAR (8) COMMENT '所在年级',
	SZBH VARCHAR (50) COMMENT '所在班号',
	BJMC VARCHAR (200) COMMENT '班级名称',
	ZYM VARCHAR (50) COMMENT '专业码',
	ZYM_MC VARCHAR (200) COMMENT '专业名称',
	SSYXM VARCHAR (50) COMMENT '所属院校码',
	SSYXM_MC VARCHAR (200) COMMENT '所属院校',
	PYCCM VARCHAR (50) COMMENT '培养层次码',
	PYCCM_MC VARCHAR (200) COMMENT '培养层次',
	SFZJH VARCHAR (20) COMMENT '身份证件号',
	CSRQ VARCHAR (10) COMMENT '出生日期',
	KH VARCHAR (30) COMMENT '卡号',
	KXL VARCHAR (30) COMMENT '卡ID(序列号)',
	JYLX VARCHAR (20) COMMENT '交易类型',
	JYJE DECIMAL (10, 2) COMMENT '交易金额',
	JYLSH VARCHAR (50) COMMENT '交易流水号',
	JYRQ VARCHAR (8) COMMENT '交易日期',
	JYSJ VARCHAR (20) COMMENT '交易时间戳',
	JYDD VARCHAR (50) COMMENT '交易地点',
	SHDM VARCHAR (20) COMMENT '商户编号',
	SHMC VARCHAR (200) COMMENT '商户名称',
	SHLBDM VARCHAR (20) COMMENT '商户类别代码',
	SHLBMC VARCHAR (200) COMMENT '商户类别名称',
	ZDJH VARCHAR (20) COMMENT 'POS编号',
	LJYKCS INT (11) COMMENT '累计刷卡次数',
	JYYE DECIMAL (10, 2) COMMENT '交易余额',
	LYDQM VARCHAR (10) COMMENT '学生来源地区码,见中华人民共和国行政区划代码表',
	LYDQM_SM VARCHAR (200) COMMENT '来源地',
	JGM VARCHAR (10) COMMENT '籍贯码',
	JGM_SM VARCHAR (200) COMMENT '籍贯'
)DISTRIBUTED BY('XH') DEFAULT CHARSET=utf8 COMMENT='一卡通交易宽表';