DROP TABLE IF EXISTS "ods"."tushu_ltk";
CREATE TABLE "ods"."ltk" (
"TXM" VARCHAR(150) NOT NULL COMMENT'条形码' ,
"DLH" VARCHAR(150) NOT NULL COMMENT'登录号' ,
"DZTM" VARCHAR(15) NOT NULL COMMENT'读者条码' ,
"WJSJ" DATETIME NOT NULL COMMENT'外借时间' ,
"YGHSJ" DATETIME NOT NULL COMMENT'应归还时间' ,
"ZJM" int(10) NOT NULL COMMENT'主键码' ,
"XNKS" int(5) NOT NULL COMMENT'虚拟库室' ,
"XJCS" int(3) NOT NULL COMMENT'续借次数' ,
"CLSJ" DATETIME NULL COMMENT'处理时间' ,
"LTKSJM" int(5) DEFAULT 0  NOT NULL COMMENT'流通库室键码' ,
"QDJM" int(10) DEFAULT 0  NOT NULL COMMENT'签到键码' ,
"FJ" VARCHAR(50) NULL COMMENT'附件',
"BZ" VARCHAR(100) NULL COMMENT'备注' ,
"JCL" VARCHAR(2000) NULL COMMENT'检查列',
"SQ" int DEFAULT 0  NULL COMMENT'授权',
"JYW" VARCHAR(2000) NULL  COMMENT'校验位',
"DT" VARCHAR(10) NULL COMMENT'增量日期字段'
)COMMENT'流通库'

