/*
#  DESCRIPTION: 一卡通交易表
#
#      OPTIONS: ---
# REQUIREMENTS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: bi.yanbo@h3c.com
#      COMPANY: h3c.bigdata
#      VERSION: 1.0
#      CREATED: 2017/06/29
#     REVIEWER:
#     REVISION: ---
*/
DROP TABLE IF EXISTS FDM.EDU_FDM_YKT_JY;
CREATE TABLE IF NOT EXISTS FDM.EDU_FDM_YKT_JY (
  KH VARCHAR(30) DEFAULT NULL COMMENT '卡号',
  KXL VARCHAR(30) DEFAULT NULL COMMENT '卡ID(序列号)',
  ZJH VARCHAR (20) NULL COMMENT '证件号、身份认证号',
  JYLX VARCHAR(20) DEFAULT NULL COMMENT '交易类型',
  JYJE DECIMAL(10,2) DEFAULT NULL COMMENT '交易金额',
  JYLSH VARCHAR(50) DEFAULT NULL COMMENT '交易流水号',
  JYRQ VARCHAR(20) DEFAULT NULL COMMENT '交易日期',
  JYSJ VARCHAR(20) DEFAULT NULL COMMENT '交易时间戳',
  JYDD VARCHAR(50) DEFAULT NULL COMMENT '交易地点',
  SHDM VARCHAR(20) DEFAULT NULL COMMENT '商户编号',
  SHMC VARCHAR(200) DEFAULT NULL COMMENT '商户名称',
  ZDJH VARCHAR(20) DEFAULT NULL COMMENT 'POS编号',
  LJYKCS INT(11) DEFAULT NULL COMMENT '累计刷卡次数',
  JYYE DECIMAL(10,2) DEFAULT NULL COMMENT '交易余额'
) DEFAULT CHARSET=utf8 COMMENT='[EDU_FAC_YKT_JY]一卡通交易表';  
