/*
#  DESCRIPTION: 一卡通商户信息表
#
#      OPTIONS: ---
# REQUIREMENTS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: bi.yanbo@h3c.com
#      COMPANY: h3c.bigdata
#      VERSION: 1.0
#      CREATED: 2017/06/29
#     REVIEWER:
#     REVISION: ---
*/
DROP TABLE IF EXISTS FDM.EDU_FDM_YKT_SHXX;
CREATE TABLE
IF NOT EXISTS FDM.EDU_FDM_YKT_SHXX (
  SHDM VARCHAR(20) DEFAULT NULL COMMENT '商户代码',
  SHMC VARCHAR(200) DEFAULT NULL COMMENT '商户名称',
  SHLBDM VARCHAR(20) DEFAULT NULL COMMENT '商户类别代码',
  SHLBMC VARCHAR(200) DEFAULT NULL COMMENT '商户类别名称',
  ZCRQ VARCHAR(8) DEFAULT NULL COMMENT '注册日期YYYYMMDD',
  ZXRQ VARCHAR(8) DEFAULT NULL COMMENT '注销日期YYYYMMDD',
  YXRQ VARCHAR(8) DEFAULT NULL COMMENT '有效日期YYYYMMDD',
  SHZT VARCHAR(30) DEFAULT NULL COMMENT '商户状态'
) DEFAULT CHARSET=utf8 COMMENT = '[一卡通商户信息表]商户信息基础表';
