/*
#  DESCRIPTION: 一卡通信息表
#
#      OPTIONS: ---
# REQUIREMENTS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: bi.yanbo@h3c.com
#      COMPANY: h3c.bigdata
#      VERSION: 1.0
#      CREATED: 2017/06/29
#     REVIEWER:
#     REVISION: ---
*/
DROP TABLE IF EXISTS FDM.EDU_FDM_YKT_XX;
CREATE TABLE
IF NOT EXISTS FDM.EDU_FDM_YKT_XX (
	`KH` VARCHAR (20) NOT NULL COMMENT '帐号/卡号',
	`HSDW` VARCHAR (40) DEFAULT NULL COMMENT '核算单位',
	`KXL` BIGINT (11) DEFAULT NULL COMMENT '卡ID(卡序列)',
	`JKXL` BIGINT (11) DEFAULT NULL COMMENT '旧卡ID(卡序列)',
	`SFXL` VARCHAR (12) DEFAULT NULL COMMENT '身份序列',
	`XM` VARCHAR (60) DEFAULT NULL COMMENT '姓名',
	`XBM` VARCHAR(1) DEFAULT NULL COMMENT '性别码 见HB性别表[edu_hb_xb]',
	`SFDM` VARCHAR (2) DEFAULT NULL COMMENT '身份代码',
	`BMDM` VARCHAR (15) DEFAULT NULL COMMENT '部门代码',
	`RXFXE` BIGINT (11) DEFAULT NULL COMMENT '日消费限额',
	`ZHYE` BIGINT (11) DEFAULT NULL COMMENT '账户余额',
	`KNYE` BIGINT (11) DEFAULT NULL COMMENT '卡内余额',
	`YJ` BIGINT (11) DEFAULT NULL COMMENT '押金',
	`DQGDYE` BIGINT (11) DEFAULT NULL COMMENT '当前过渡余额',
	`SCGDYE` BIGINT (11) DEFAULT NULL COMMENT '上次过渡余额',
	`DQBZXLH` BIGINT (11) DEFAULT NULL COMMENT '当期补助序列号',
	`SCBZXLH` BIGINT (11) DEFAULT NULL COMMENT '上次补助序列号',
	`LJYKCS` BIGINT (11) DEFAULT NULL COMMENT '累计用卡次数',
	`ZDZZJJE` BIGINT (11) DEFAULT NULL COMMENT '自动转账警戒额',
	`ZDZZE` BIGINT (11) DEFAULT NULL COMMENT '自动转账额',
	`GLFJFL` BIGINT (11) DEFAULT NULL COMMENT '管理附加费率',
	`CXMM` VARCHAR (16) DEFAULT NULL COMMENT '查询密码',
	`YHZH` VARCHAR (30) DEFAULT NULL COMMENT '银行帐号',
	`ZJH` VARCHAR (20) DEFAULT NULL COMMENT '证件号',
	`ZJLX` VARCHAR (3) DEFAULT NULL COMMENT '证件类型',
	`XH` VARCHAR(20) DEFAULT NULL COMMENT '学工号',
	`YDDH` VARCHAR (30) DEFAULT NULL COMMENT ' 移动电话 ',
	`KHRQ` VARCHAR (8) DEFAULT NULL COMMENT '开户日期/注册日期YYYYMMDD',
	`YXRQ` VARCHAR (8) DEFAULT NULL COMMENT '有效日期YYYYMMDD',
	`KLX` VARCHAR (3) DEFAULT NULL COMMENT ' 卡类型 ',
	`ZHBJ` VARCHAR (16) DEFAULT NULL COMMENT ' 账户标记 ',
	`GXRQ` VARCHAR (8) DEFAULT NULL COMMENT ' 更新日期 ',
	`SZQM` VARCHAR (8) DEFAULT NULL COMMENT '数字签名 ',
	`KPZT` VARCHAR (30) DEFAULT NULL COMMENT '卡片状态 '
) DEFAULT CHARSET=utf8 COMMENT = '[一卡通信息表]一卡通当前基础信息';
