#
#        USAGE: ./ edu_adm_kc_cj_zyhz_da.sh
#
#  DESCRIPTION: 课程成绩专业数据汇总
#
#      OPTIONS: ---
# REQUIREMENTS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: bi.yanbo@h3c.com
#      COMPANY: h3c.bigdata
#      VERSION: 1.0
#      CREATED: 2017/06/30
#     REVIEWER:
#     REVISION: ---

#!/usr/bin/env bash
base=$(dirname $0)
conn=$1
sql="TRUNCATE TABLE ADM.EDU_ADM_KC_CJ_ZYHZ_DA;
INSERT INTO ADM.EDU_ADM_KC_CJ_ZYHZ_DA(ZYM, PJCJ, GKS, PJCJ_HIGH, PJCJ_LOW, GKS_HIGH, GKS_LOW)
SELECT A1.ZYM, A1.PJCJ, B1.GKS, C1.PJCJ_HIGH, C1.PJCJ_LOW, D1.GKS_HIGH, D1.GKS_LOW
FROM
(
  SElECT A.ZYM, SUM(A.KCCJ_JG * A.XF)/SUM(A.XF) AS PJCJ
  FROM
  (
    SELECT XH, XN, XQM, KCH, XF, ZYM, MAX(KCCJ_JG) AS KCCJ_JG
    FROM GDM.EDU_GDM_KC_KCCJ_DA
    WHERE KCCJ_JG IS NOT NULL
    GROUP BY XH, XN, XQM, KCH, XF, ZYM
  ) A
  GROUP BY ZYM
) A1
LEFT JOIN
(
  SELECT B.ZYM, COUNT(DISTINCT KCH)/COUNT(DISTINCT XH) AS GKS
  FROM 
  (
    SELECT XH, XN, XQM, KCH, ZYM, MAX(KCCJ_JG) AS KCCJ_JG
    FROM GDM.EDU_GDM_KC_KCCJ_DA
    WHERE KCCJ_JG IS NOT NULL
    GROUP BY XH, XN, XQM, KCH, ZYM
  ) B
  WHERE KCCJ_JG < '60'
  GROUP BY ZYM
) B1 ON A1.ZYM = B1.ZYM
LEFT JOIN
(
	SELECT AA.ZYM, MAX(AA.PJCJ) AS PJCJ_HIGH, MIN(AA.PJCJ) AS PJCJ_LOW
	FROM
	(
		  SElECT A.XH, A.ZYM, SUM(A.KCCJ_JG * A.XF)/SUM(A.XF) AS PJCJ
		  FROM
		  (
		    SELECT XH, XN, XQM, KCH, XF, ZYM, MAX(KCCJ_JG) AS KCCJ_JG
		    FROM GDM.EDU_GDM_KC_KCCJ_DA
		    WHERE KCCJ_JG IS NOT NULL
		    GROUP BY XH, XN, XQM, KCH, XF, ZYM
		  ) A
		  GROUP BY A.XH, A.ZYM
 	) AA
 	GROUP BY AA.ZYM
) C1 ON A1.ZYM = C1.ZYM
LEFT JOIN 
(
	SELECT BB.ZYM, MAX(BB.GKS) AS GKS_HIGH, MIN(BB.GKS) AS GKS_LOW
	FROM
	(
		  SELECT B.XH, B.ZYM, COUNT(DISTINCT KCH) AS GKS
		  FROM 
		  (
		    SELECT XH, ZYM, XN, XQM, KCH, MAX(KCCJ_JG) AS KCCJ_JG
		    FROM GDM.EDU_GDM_KC_KCCJ_DA
		    WHERE KCCJ_JG IS NOT NULL
		    GROUP BY XH, XN, XQM, KCH, ZYM
		  ) B
		  WHERE KCCJ_JG < '60'
		  GROUP BY B.XH, B.ZYM
	) BB
	GROUP BY BB.ZYM
) D1 ON A1.ZYM = D1.ZYM"

now=`date +%Y-%m-%d:%H:%M:%S`
echo "$now executing:$sql"
    su - mpp -c "gccli $conn -e '$sql'"
status=$?
if [ $status -eq 0 ]; then
    echo "--generated successfully"
else echo "-- generated to fail"
fi
