-- ----------------------------
-- MPP(遗留4月的没有抽取，待规划增量)
-- ----------------------------
DROP TABLE "ods"."SH_T_APPSDK_STEP";
CREATE TABLE "ods"."SH_T_APPSDK_STEP" (
"APPID" int(10) NOT NULL COMMENT '用户ID，对应T_STUDENT_INFO的USER_ID',
"APPUSER" VARCHAR(20 ) NOT NULL COMMENT '用户账号',
"DEVICE_ID" VARCHAR(20 ) NOT NULL COMMENT '手环ID',
"CMDID" VARCHAR(4 ) NOT NULL ,
"DATA1" VARCHAR(40 ) NULL ,
"DATA1_INT" int(9) NULL COMMENT '运动步数（一小时的步数统计数）',
"DATA2" VARCHAR(40 ) NULL ,
"DATA2_INT" int(9) NULL ,
"DATA3" VARCHAR(40 ) NULL ,
"DATA3_INT" int(9) NULL ,
"DATATIME" DATEtime NOT NULL COMMENT '步数对应的小时时间，取值为步数发生时间所在小时的最后一秒',
"SYS_DATE" DATEtime NOT NULL 
)COMMENT'运动步数';

/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.4.0

Source Server         : 10.2.15.215-shouhuan
Source Server Version : 110200
Source Host           : 10.2.15.215:11521
Source Schema         : SHOUHUAN

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-04-02 09:35:22
*/


-- ----------------------------
-- Table structure for T_APPSDK_STEP_201612
-- ----------------------------
DROP TABLE "SHOUHUAN"."T_APPSDK_STEP_201612";
CREATE TABLE "SHOUHUAN"."T_APPSDK_STEP_201612" (
"APPID" NUMBER(10) NOT NULL ,
"APPUSER" VARCHAR2(20 BYTE) NOT NULL ,
"DEVICE_ID" VARCHAR2(20 BYTE) NOT NULL ,
"CMDID" VARCHAR2(4 BYTE) NOT NULL ,
"DATA1" VARCHAR2(40 BYTE) NULL ,
"DATA1_INT" NUMBER(9) NULL ,
"DATA2" VARCHAR2(40 BYTE) NULL ,
"DATA2_INT" NUMBER(9) NULL ,
"DATA3" VARCHAR2(40 BYTE) NULL ,
"DATA3_INT" NUMBER(9) NULL ,
"DATATIME" DATE NOT NULL ,
"SYS_DATE" DATE NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Indexes structure for table T_APPSDK_STEP_201612
-- ----------------------------
CREATE INDEX "SHOUHUAN"."I_APPSDK_STEP_201612_1"
ON "SHOUHUAN"."T_APPSDK_STEP_201612" ("APPID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SHOUHUAN"."I_APPSDK_STEP_201612_2"
ON "SHOUHUAN"."T_APPSDK_STEP_201612" ("DATATIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table T_APPSDK_STEP_201612
-- ----------------------------
ALTER TABLE "SHOUHUAN"."T_APPSDK_STEP_201612" ADD CHECK ("APPID" IS NOT NULL);
ALTER TABLE "SHOUHUAN"."T_APPSDK_STEP_201612" ADD CHECK ("APPUSER" IS NOT NULL);
ALTER TABLE "SHOUHUAN"."T_APPSDK_STEP_201612" ADD CHECK ("DEVICE_ID" IS NOT NULL);
ALTER TABLE "SHOUHUAN"."T_APPSDK_STEP_201612" ADD CHECK ("CMDID" IS NOT NULL);
ALTER TABLE "SHOUHUAN"."T_APPSDK_STEP_201612" ADD CHECK ("DATATIME" IS NOT NULL);
ALTER TABLE "SHOUHUAN"."T_APPSDK_STEP_201612" ADD CHECK ("SYS_DATE" IS NOT NULL);
