-- ----------------------------
-- MPP
-- ----------------------------
DROP TABLE "ods"."SH_T_STUDENT_INFO";
CREATE TABLE "ods"."SH_T_STUDENT_INFO" (
"USER_ID" int(10) NULL ,
"STUDENT_ID" VARCHAR(30 ) NULL COMMENT '学号',
"STUDENT_NAME" VARCHAR(60 ) NULL COMMENT '姓名',
"STATUS" int(2) NULL COMMENT '状态，0：已封锁，1：未领取，2：已绑定App用户，3：未绑定App用户',
"XY" VARCHAR(100 ) NULL COMMENT '学院',
"X" VARCHAR(100 ) NULL COMMENT '系',
"ZY" VARCHAR(100 ) NULL COMMENT '专业',
"BJ" VARCHAR(100 ) NULL COMMENT '班级',
"REMARK1" VARCHAR(30 ) NULL ,
"REMARK2" VARCHAR(100 ) NULL ,
"REMARK3" VARCHAR(200 ) NULL ,
"BIND_TIME" DATEtime NULL COMMENT '绑定时间',
"USER_TYPE" int(2) NULL COMMENT '1：老师，2：学生，3：安保',
"GET_TIME" DATEtime NULL COMMENT '领取时间',
"GRADE" int(4) NULL ,
"SEX" VARCHAR(2 ) NULL COMMENT '性别',
"PY" VARCHAR(800 ) NULL ,
"JP" VARCHAR(400 ) NULL ,
"OP_MAN" VARCHAR(30 ) NULL ,
"OP_TIME" DATEtime NULL 
)COMMENT '用户信息表'

/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.4.0

Source Server         : 10.2.15.215-shouhuan
Source Server Version : 110200
Source Host           : 10.2.15.215:11521
Source Schema         : SHOUHUAN

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-04-02 09:34:21
*/


-- ----------------------------
-- Table structure for T_STUDENT_INFO
-- ----------------------------
DROP TABLE "SHOUHUAN"."T_STUDENT_INFO";
CREATE TABLE "SHOUHUAN"."T_STUDENT_INFO" (
"USER_ID" NUMBER(10) NULL ,
"STUDENT_ID" VARCHAR2(30 BYTE) NULL ,
"STUDENT_NAME" VARCHAR2(60 BYTE) NULL ,
"STATUS" NUMBER(1) NULL ,
"XY" VARCHAR2(100 BYTE) NULL ,
"X" VARCHAR2(100 BYTE) NULL ,
"ZY" VARCHAR2(100 BYTE) NULL ,
"BJ" VARCHAR2(100 BYTE) NULL ,
"REMARK1" VARCHAR2(30 BYTE) NULL ,
"REMARK2" VARCHAR2(100 BYTE) NULL ,
"REMARK3" VARCHAR2(200 BYTE) NULL ,
"BIND_TIME" DATE NULL ,
"USER_TYPE" NUMBER(1) NULL ,
"GET_TIME" DATE NULL ,
"GRADE" NUMBER(4) NULL ,
"SEX" CHAR(1 BYTE) NULL ,
"PY" VARCHAR2(800 BYTE) NULL ,
"JP" VARCHAR2(400 BYTE) NULL ,
"OP_MAN" VARCHAR2(30 BYTE) NULL ,
"OP_TIME" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Indexes structure for table T_STUDENT_INFO
-- ----------------------------
CREATE UNIQUE INDEX "SHOUHUAN"."I_STUDENT_INFO_1"
ON "SHOUHUAN"."T_STUDENT_INFO" ("STUDENT_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SHOUHUAN"."I_STUDENT_INFO_10"
ON "SHOUHUAN"."T_STUDENT_INFO" ("PY" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SHOUHUAN"."I_STUDENT_INFO_11"
ON "SHOUHUAN"."T_STUDENT_INFO" ("JP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SHOUHUAN"."I_STUDENT_INFO_2"
ON "SHOUHUAN"."T_STUDENT_INFO" ("STUDENT_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SHOUHUAN"."I_STUDENT_INFO_3"
ON "SHOUHUAN"."T_STUDENT_INFO" ("USER_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SHOUHUAN"."I_STUDENT_INFO_4"
ON "SHOUHUAN"."T_STUDENT_INFO" ("BIND_TIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SHOUHUAN"."I_STUDENT_INFO_5"
ON "SHOUHUAN"."T_STUDENT_INFO" ("XY" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SHOUHUAN"."I_STUDENT_INFO_7"
ON "SHOUHUAN"."T_STUDENT_INFO" ("ZY" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SHOUHUAN"."I_STUDENT_INFO_8"
ON "SHOUHUAN"."T_STUDENT_INFO" ("BJ" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SHOUHUAN"."I_STUDENT_INFO_9"
ON "SHOUHUAN"."T_STUDENT_INFO" ("STATUS" ASC)
LOGGING
VISIBLE;
